# Noizu.Util.Node.Base Container

FROM registry.noizu.com/noizu.debian.jessie:latest
MAINTAINER Keith Brings <keith.brings@noizu.com>

#====================================================#
# Setup Instance                                     #
#====================================================#
ADD ./scripts/setup.sh /tmp/scripts/noizu.util.node.base/setup.sh
RUN /tmp/scripts/noizu.util.node.base/setup.sh
